### ISSUE TITLE
Employee Personality Trait Bug

### ISSUE THREAD

**Issue by Piny0CRT** [elkay235/Black-Order-Dialogue-Mod#10]
When hiring an employee, hovering over an employee with the "Husk Follower" Trait shows the following error. 
The consol pops up saying that Text 'personalitytrait.HuskFollower' not found

![bug](https://user-images.githubusercontent.com/92065642/136863698-0c627da3-b52c-45eb-94e7-cd9207c9d555.png)
![bug 2](https://user-images.githubusercontent.com/92065642/136863705-9f1725ab-ccea-4685-9c93-63149f4fcfe5.png)

**Comment by elkay235** [comment]
For those who need clear reasoning as to what this game bug is:

Every time you make a campaign or multiplayer mission, the game will randomly pick six traits from both vanilla and modded sources, like this one. This will not change until a new campaign/mission is generated, where it will pick another six. Nothing I can do about this.

As for the above screenshot by Piny, yeah I am a moron and may have fucked up something there, but either way it probably would not have worked because of this game bug and the fact that I update this mod too much.

**Comment by elkay235** [comment]
Update pushed. Closing.
